#!/usr/bin/env php
<?php

use Webgraphe\Phollow\Application;
use Webgraphe\Phollow\Configuration;

error_reporting(E_ALL);
ini_set('display_errors', true);

if (version_compare('5.6.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of Webgraphe Phollow is supported on PHP 5.6+' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PHOLLOW_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('PHOLLOW_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        implode(
            PHP_EOL,
            [
                'You need to set up the project dependencies using Composer:',
                null,
                '    composer install',
                null,
                'You can learn all about Composer on https://getcomposer.org/.',
                null
            ]
        )
    );

    die(1);
}

/** @noinspection PhpIncludeInspection */
require PHOLLOW_COMPOSER_INSTALL;

try {
    $configuration = Configuration::fromGlobals();
    if ($configuration->showHelp()) {
        die($configuration->getUsage());
    }
    if ($configuration->showConfig()) {
        die($configuration->getConfig());
    }

    $app = Application::create($configuration);
    $app->run();
} catch (\Exception $e) {
    echo $e->getMessage() . PHP_EOL;
    echo $e->getTraceAsString() . PHP_EOL;

    die(1);
}
